// Generated by scripts/generate-image-manifest.mjs. Do not edit by hand.
export const imageManifest: Record<string, string[]> = {
  "/images": [
    "/images/hero-black-man-watch.png"
  ],
  "/images/cartier/tank-must": [
    "/images/cartier/tank-must/1.webp"
  ],
  "/images/citizen/series-8-skeleton": [
    "/images/citizen/series-8-skeleton/1.webp"
  ],
  "/images/longines/master-collection": [
    "/images/longines/master-collection/1.webp"
  ],
  "/images/omega/speedmaster-moonwatch": [
    "/images/omega/speedmaster-moonwatch/1.webp"
  ],
  "/images/rolex/datejust-41": [
    "/images/rolex/datejust-41/1.webp"
  ],
  "/images/tag-heuer/carrera-chronograph": [
    "/images/tag-heuer/carrera-chronograph/1.webp"
  ],
  "/images/tissot/prx-powermatic-80": [
    "/images/tissot/prx-powermatic-80/1.webp"
  ],
  "/images/tudor/black-bay-58": [
    "/images/tudor/black-bay-58/1.webp"
  ]
};
